---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      #- recipe[testing::default]
      - recipe[testing::default]
      - recipe[testing::logrotate-cpp]
      - recipe[testing::logrotate-general]

    attributes:
